version: "3.9"

services:
  ghostfarm:
    build: .
    container_name: twitch_ghost_farm
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app  # Монтируем локальную папку app прямо в /app контейнера
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped